"""基础服务层。

依赖方向：``services`` 可以用 ``engine``，但不反过来。模型层用 services，
services 不知道模型层的存在。

    map/          地图服务：全球层（H3）+ 局部平面网格 + 战区路由 + 数据层
    spatial.py    空间索引：网格 → 实体的快速查询，雷达探测的地基
    bus.py        事件总线：模型 → 视图/日志/统计 的单向通知
    random.py     确定性随机流：按 (实体, 用途) 分流，保证可复现
    registry.py   实体注册表：身份管理（低频）
    store.py      实体状态存储：位置/航迹/损耗/消息（高频），按视图收窄访问
    params.py     参数模式：想定参数必须先声明，含单位换算
    type_registry.py  原型与差量实例、组件类注册、三层参数覆盖
    input/        想定语言：Lexer（分词）+ Parser（块结构）
    scenario.py   想定语义：键名校验、单位换算、引用校验 → ScenarioSpec
    formation.py  编队树：谁属于谁（声明式拓扑，聚合的前提）
    command.py    指挥关系三层：行政隶属 / 作战归属 / 指令通道
    situation.py  态势投影：EntityStore → 某方认知的战场（视野限制 + 编队汇聚）
    orchestrator/ 分级控制骨架：Intent（意图）/ Task（任务）/ 命令台账
    library.py    参数库：型号参数存进数据库，想定只写型号名

本层是唯一允许使用 numpy / h3 等第三方库的地方；引擎层保持零依赖。
"""

from .bus import EventBus, Signal, Subscription
from .command import (
    Attachment,
    CommandChain,
    Coordination,
    Directive,
    TimeWindow,
)
from .orchestrator import (
    ASSIGNEE_LABELS,
    ASSIGNEE_LEVELS,
    INTENT_ACTIVE,
    INTENT_CANCELLED,
    INTENT_EXPIRED,
    INTENT_LABELS,
    INTENT_STATES,
    INTENT_SUPERSEDED,
    INTENT_TRANSITIONS,
    KIND_DEFEND,
    KIND_ENGAGE,
    KIND_HOLD,
    KIND_LABELS,
    KIND_MOVE,
    KIND_OCCUPY,
    KIND_RECON,
    KIND_REPORT,
    KIND_REQUIREMENTS,
    LEVEL_ENTITY,
    LEVEL_UNIT,
    NOBODY,
    PRIORITIES,
    PRIORITY_IMPORTANT,
    PRIORITY_LABELS,
    PRIORITY_ROUTINE,
    PRIORITY_URGENT,
    REQUIREMENT_LABELS,
    STATE_ABORTED,
    STATE_ACTIVE,
    STATE_COMPLETED,
    STATE_EXPIRED,
    STATE_FAILED,
    STATE_LABELS,
    STATE_PENDING,
    TASK_KINDS,
    TASK_STATES,
    TASK_TRANSITIONS,
    TERMINAL_INTENT_STATES,
    TERMINAL_STATES,
    CommandLedger,
    Intent,
    Objective,
    StateChange,
    SweepReport,
    Task,
    TaskBatch,
    TaskError,
    missing_requirements,
    world_checker,
)
from .formation import UNASSIGNED_ID, Formation, FormationTree
from .library import (
    KIND_COMPONENT,
    KIND_PLATFORM,
    DuplicateModelError,
    LibraryError,
    LibrarySchemaError,
    Literal,
    ModelRecord,
    ParamLibrary,
)
from .map import Axial
from .situation import (
    BASIS_ADMINISTRATIVE,
    BASIS_OPERATIONAL,
    UNIDENTIFIED_CONTACT,
    UNIDENTIFIED_UNIT,
    DigestOptions,
    EntityInfo,
    FormationInfo,
    Situation,
    SituationProjector,
    digest,
    format_sim_time,
)
from .params import (
    BASE_UNIT,
    CoordValue,
    Dimension,
    MissingParameterError,
    ParamError,
    ParamKind,
    ParamSet,
    ParamSpec,
    Params,
    UnknownParameterError,
    WithUnit,
    with_unit,
)
from .random import (
    SequenceGenerator,
    Stream,
    RandomPool,
    EntityStreams,
    bernoulli,
    jitter,
    seed_for_run,
)
from .registry import EntityRegistry, RegisteredEntity
from .scenario import (
    PROVIDERS,
    DecisionProfile,
    PlatformDecl,
    ScenarioError,
    ScenarioSpec,
    SimulationSettings,
    ZoneDecl,
    build_spec,
    load_scenario,
)
from .store import (
    DAMAGE_DESTROYED,
    DAMAGE_INTACT,
    CellRef,
    CommView,
    Contact,
    Effect,
    EngagementView,
    EntityStore,
    GlobalCellRef,
    KinematicsTable,
    LocalCellRef,
    Message,
    MoverView,
    SensorView,
)
from .type_registry import (
    ComponentFactory,
    ComponentRegistry,
    ComponentSpec,
    ComponentType,
    DuplicateComponentError,
    DuplicateTypeError,
    InheritanceCycleError,
    PlatformType,
    ResolvedComponent,
    ResolvedPlatform,
    TypeDefinitionError,
    TypeRegistry,
    UnknownComponentError,
    UnknownTypeError,
    default_registry,
    register_component,
)
from .spatial import (
    BEARING_OF_DIRECTION,
    IndexStats,
    LayeredSpatialIndex,
    SpatialIndex,
    approximate_distance_m,
    bearing_between,
    bearing_of_direction,
    bearing_of_offset,
    cells_in_cone,
    cells_in_disk,
    cells_in_sector,
    cells_within_bearing,
    direction_from_bearing,
)

__all__ = [
    # -- 编队与指挥关系 --
    "FormationTree",
    "Formation",
    "UNASSIGNED_ID",
    "CommandChain",
    "TimeWindow",
    "Attachment",
    "Directive",
    "Coordination",
    # -- 态势投影 --
    "BASIS_ADMINISTRATIVE",
    "BASIS_OPERATIONAL",
    "UNIDENTIFIED_CONTACT",
    "UNIDENTIFIED_UNIT",
    # -- 参数库 --
    "ParamLibrary",
    "ModelRecord",
    "Literal",
    "LibraryError",
    "LibrarySchemaError",
    "DuplicateModelError",
    "KIND_COMPONENT",
    "KIND_PLATFORM",
    "SituationProjector",
    "Situation",
    "FormationInfo",
    "EntityInfo",
    "DigestOptions",
    "digest",
    "format_sim_time",
    # -- 分级控制骨架（M5a）--
    "Intent",
    "Task",
    "Objective",
    "TaskBatch",
    "CommandLedger",
    "SweepReport",
    "StateChange",
    "TaskError",
    "NOBODY",
    "world_checker",
    "missing_requirements",
    "ASSIGNEE_LEVELS",
    "ASSIGNEE_LABELS",
    "LEVEL_ENTITY",
    "LEVEL_UNIT",
    "TASK_KINDS",
    "KIND_MOVE",
    "KIND_OCCUPY",
    "KIND_RECON",
    "KIND_DEFEND",
    "KIND_HOLD",
    "KIND_ENGAGE",
    "KIND_REPORT",
    "KIND_LABELS",
    "KIND_REQUIREMENTS",
    "REQUIREMENT_LABELS",
    "TASK_STATES",
    "TASK_TRANSITIONS",
    "TERMINAL_STATES",
    "STATE_PENDING",
    "STATE_ACTIVE",
    "STATE_COMPLETED",
    "STATE_FAILED",
    "STATE_ABORTED",
    "STATE_EXPIRED",
    "STATE_LABELS",
    "INTENT_STATES",
    "INTENT_TRANSITIONS",
    "TERMINAL_INTENT_STATES",
    "INTENT_ACTIVE",
    "INTENT_SUPERSEDED",
    "INTENT_EXPIRED",
    "INTENT_CANCELLED",
    "INTENT_LABELS",
    "PRIORITIES",
    "PRIORITY_ROUTINE",
    "PRIORITY_IMPORTANT",
    "PRIORITY_URGENT",
    "PRIORITY_LABELS",
    # -- 空间索引 --
    "SpatialIndex",
    "LayeredSpatialIndex",
    "IndexStats",
    "cells_in_cone",
    "cells_in_disk",
    "cells_in_sector",
    "direction_from_bearing",
    "bearing_of_direction",
    "bearing_between",
    "cells_within_bearing",
    "approximate_distance_m",
    "bearing_of_offset",
    "BEARING_OF_DIRECTION",
    # -- 实体注册表 --
    "EntityRegistry",
    "RegisteredEntity",
    # -- 实体状态存储 --
    "EntityStore",
    "KinematicsTable",
    "Axial",
    "LocalCellRef",
    "GlobalCellRef",
    "CellRef",
    "Contact",
    "Message",
    "Effect",
    "SensorView",
    "MoverView",
    "EngagementView",
    "CommView",
    "DAMAGE_INTACT",
    "DAMAGE_DESTROYED",
    # -- 参数模式 --
    "Params",
    "ParamSpec",
    "ParamSet",
    "ParamKind",
    "Dimension",
    "ParamError",
    "UnknownParameterError",
    "MissingParameterError",
    "CoordValue",
    "WithUnit",
    "with_unit",
    "BASE_UNIT",
    # -- 类型系统 --
    "TypeRegistry",
    "ComponentRegistry",
    "ComponentFactory",
    "ComponentType",
    "ComponentSpec",
    "PlatformType",
    "ResolvedComponent",
    "ResolvedPlatform",
    "TypeDefinitionError",
    "UnknownTypeError",
    "DuplicateTypeError",
    "InheritanceCycleError",
    "UnknownComponentError",
    "DuplicateComponentError",
    "register_component",
    "default_registry",
    # -- 想定语言 --
    "load_scenario",
    "build_spec",
    "ScenarioSpec",
    "ScenarioError",
    "ZoneDecl",
    "PlatformDecl",
    "DecisionProfile",
    "SimulationSettings",
    "PROVIDERS",
    # -- 事件总线 --
    "EventBus",
    "Signal",
    "Subscription",
    # -- 确定性随机 --
    "RandomPool",
    "EntityStreams",
    "Stream",
    "SequenceGenerator",
    "seed_for_run",
    "bernoulli",
    "jitter",
]
